"""empty message

Revision ID: 1d3066a8b1dd
Revises: 
Create Date: 2021-10-13 22:58:33.751484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3066a8b1dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyzes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('handle', sa.VARCHAR(length=80), nullable=False),
    sa.Column('total', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
