"""empty message

Revision ID: 3528e2d48cd3
Revises: 1d3066a8b1dd
Create Date: 2021-10-13 23:10:44.365332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3528e2d48cd3'
down_revision = '1d3066a8b1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analises', sa.Column('friends', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analises', 'friends')
    # ### end Alembic commands ###
