"""empty message

Revision ID: 619207295bd8
Revises: 0b2f74965b1c
Create Date: 2022-09-04 14:28:27.289857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619207295bd8'
down_revision = '0b2f74965b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analises', 'friends')
    op.drop_column('analises', 'sentiment')
    op.drop_column('analises', 'network')
    op.drop_column('analises', 'temporal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analises', sa.Column('temporal', sa.VARCHAR(length=120), nullable=True))
    op.add_column('analises', sa.Column('network', sa.VARCHAR(length=120), nullable=True))
    op.add_column('analises', sa.Column('sentiment', sa.VARCHAR(length=120), nullable=True))
    op.add_column('analises', sa.Column('friends', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
