"""empty message

Revision ID: cc5846eb4bde
Revises: 6b9a6d061aa9
Create Date: 2021-10-14 12:54:24.662955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5846eb4bde'
down_revision = '6b9a6d061aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analises', sa.Column('pegabot_version', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analises', 'pegabot_version')
    # ### end Alembic commands ###
