"""empty message

Revision ID: d5e8c24d715d
Revises: 6c7352e536fe
Create Date: 2024-01-10 11:44:11.074656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e8c24d715d'
down_revision = '6c7352e536fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analises', sa.Column('twitter_statuses_count', sa.Integer(), nullable=True))
    op.add_column('analises', sa.Column('twitter_favourites_count', sa.Integer(), nullable=True))
    op.drop_column('analises', 'temporal')
    op.drop_column('analises', 'twitter_default_profile')
    op.drop_column('analises', 'twitter_profile_image')
    op.drop_column('analises', 'twitter_is_protected')
    op.drop_column('analises', 'twitter_location')
    op.drop_column('analises', 'sentiment')
    op.drop_column('analises', 'twitter_lang')
    op.drop_column('analises', 'friends')
    op.drop_column('analises', 'handle')
    op.drop_column('analises', 'network')
    op.drop_column('analises', 'twitter_withheld_in_countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analises', sa.Column('twitter_withheld_in_countries', sa.VARCHAR(length=255), nullable=True))
    op.add_column('analises', sa.Column('network', sa.VARCHAR(length=120), nullable=True))
    op.add_column('analises', sa.Column('handle', sa.VARCHAR(length=80), nullable=False))
    op.add_column('analises', sa.Column('friends', sa.VARCHAR(length=120), nullable=True))
    op.add_column('analises', sa.Column('twitter_lang', sa.TIMESTAMP(), nullable=True))
    op.add_column('analises', sa.Column('sentiment', sa.VARCHAR(length=120), nullable=True))
    op.add_column('analises', sa.Column('twitter_location', sa.VARCHAR(length=120), nullable=True))
    op.add_column('analises', sa.Column('twitter_is_protected', sa.BOOLEAN(), nullable=True))
    op.add_column('analises', sa.Column('twitter_profile_image', sa.VARCHAR(length=255), nullable=True))
    op.add_column('analises', sa.Column('twitter_default_profile', sa.VARCHAR(length=255), nullable=True))
    op.add_column('analises', sa.Column('temporal', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('analises', 'twitter_favourites_count')
    op.drop_column('analises', 'twitter_statuses_count')
    # ### end Alembic commands ###
