"""empty message

Revision ID: db5e36594fbb
Revises: 3528e2d48cd3
Create Date: 2021-10-13 23:13:33.495696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5e36594fbb'
down_revision = '3528e2d48cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analises', sa.Column('network', sa.String(length=120), nullable=True))
    op.add_column('analises', sa.Column('sentiment', sa.String(length=120), nullable=True))
    op.add_column('analises', sa.Column('temporal', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analises', 'temporal')
    op.drop_column('analises', 'sentiment')
    op.drop_column('analises', 'network')
    # ### end Alembic commands ###
